travis:
  secure:
    BINSTAR_TOKEN: EDet7Z7POuInhbEUUHm5OL74i+eyPp4Taa/UraPIAEUWTU33W8VORbl42gB+/o1nyW5UGP08mwGK/gVVj6LHZk9Hk0LyqgS1qVR2uHztWHipssGch+Zw5o1SlnX83lmeQK3PIdx/ALm2OrER+06KiiFMZOrVSH6EaTS/kdJCEqL3pm21xfh7O16DuL61nMe7LAZ6MIZ3y9FilVzwg5esoj9iJedKaFkT0CkGI7sK/TeQG2dHzLVDAu1YBGCjxBETgbMQfHj5UqG1WAuxILqQYXTBWtN1g9yzwWR+ZBP7DgLpVkb3aBMy3FTvh2RtzhFcOwlU/IzJfdZq98YZmqknTKxFOZCWduw6Unc0Qdc0mRMWk9V6CwA1Ybe1yuU+yWHhjE742Bnx+zxZpX+Q/fpjNH4q0xreLr6aqAE00hO/4h+d+jYASRZ8pGXI0N9pVUaHCXmPUdcUwi3gAdZejCZoFFNHMqNvj7JhK25saSfuvXdHjhCyuf3lT49bZ97Eb0mEI14BgzM8UgLX2CL8Qrr2z9QZoCUCRewIbqhG96wzZPNyk9LC0+S9NkUExFC85AAEdx3LTuRcY6wJAYh4tTKAm3KhI27hd2zhf1TUqwE0B+aiZiszguAgaCqnesKI+tBsH5u8QGH43dq/rBTD3MpBzzmAAB7LAbjRT+h0OzcHLvc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
